// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: gabriel_protocol/gabriel.proto

package gabrielpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GabrielService_Session_FullMethodName = "/gabriel.GabrielService/Session"
)

// GabrielServiceClient is the client API for GabrielService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service for Gabriel clients.
type GabrielServiceClient interface {
	// Start a new session with a Gabriel server.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromClient, ToClient], error)
}

type gabrielServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGabrielServiceClient(cc grpc.ClientConnInterface) GabrielServiceClient {
	return &gabrielServiceClient{cc}
}

func (c *gabrielServiceClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromClient, ToClient], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GabrielService_ServiceDesc.Streams[0], GabrielService_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FromClient, ToClient]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GabrielService_SessionClient = grpc.BidiStreamingClient[FromClient, ToClient]

// GabrielServiceServer is the server API for GabrielService service.
// All implementations must embed UnimplementedGabrielServiceServer
// for forward compatibility.
//
// gRPC service for Gabriel clients.
type GabrielServiceServer interface {
	// Start a new session with a Gabriel server.
	Session(grpc.BidiStreamingServer[FromClient, ToClient]) error
	mustEmbedUnimplementedGabrielServiceServer()
}

// UnimplementedGabrielServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGabrielServiceServer struct{}

func (UnimplementedGabrielServiceServer) Session(grpc.BidiStreamingServer[FromClient, ToClient]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedGabrielServiceServer) mustEmbedUnimplementedGabrielServiceServer() {}
func (UnimplementedGabrielServiceServer) testEmbeddedByValue()                        {}

// UnsafeGabrielServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GabrielServiceServer will
// result in compilation errors.
type UnsafeGabrielServiceServer interface {
	mustEmbedUnimplementedGabrielServiceServer()
}

func RegisterGabrielServiceServer(s grpc.ServiceRegistrar, srv GabrielServiceServer) {
	// If the following call panics, it indicates UnimplementedGabrielServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GabrielService_ServiceDesc, srv)
}

func _GabrielService_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GabrielServiceServer).Session(&grpc.GenericServerStream[FromClient, ToClient]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GabrielService_SessionServer = grpc.BidiStreamingServer[FromClient, ToClient]

// GabrielService_ServiceDesc is the grpc.ServiceDesc for GabrielService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GabrielService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gabriel.GabrielService",
	HandlerType: (*GabrielServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _GabrielService_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gabriel_protocol/gabriel.proto",
}
