// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: gabriel.proto

package gabrielpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadType int32

const (
	PayloadType_PAYLOAD_TYPE_UNSPECIFIED PayloadType = 0
	PayloadType_TEXT                     PayloadType = 1
	PayloadType_IMAGE                    PayloadType = 2
	PayloadType_AUDIO                    PayloadType = 3
	PayloadType_VIDEO                    PayloadType = 4
	PayloadType_CONTROL                  PayloadType = 5
	PayloadType_OTHER                    PayloadType = 100
)

// Enum value maps for PayloadType.
var (
	PayloadType_name = map[int32]string{
		0:   "PAYLOAD_TYPE_UNSPECIFIED",
		1:   "TEXT",
		2:   "IMAGE",
		3:   "AUDIO",
		4:   "VIDEO",
		5:   "CONTROL",
		100: "OTHER",
	}
	PayloadType_value = map[string]int32{
		"PAYLOAD_TYPE_UNSPECIFIED": 0,
		"TEXT":                     1,
		"IMAGE":                    2,
		"AUDIO":                    3,
		"VIDEO":                    4,
		"CONTROL":                  5,
		"OTHER":                    100,
	}
)

func (x PayloadType) Enum() *PayloadType {
	p := new(PayloadType)
	*p = x
	return p
}

func (x PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_gabriel_proto_enumTypes[0].Descriptor()
}

func (PayloadType) Type() protoreflect.EnumType {
	return &file_gabriel_proto_enumTypes[0]
}

func (x PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadType.Descriptor instead.
func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{0}
}

type StatusCode int32

const (
	// Success.
	StatusCode_SUCCESS StatusCode = 0
	// Errors whose cause is not known.
	StatusCode_UNSPECIFIED_ERROR StatusCode = 1
	// Errors that are not related to Gabriel but rather to the engine
	// itself.
	StatusCode_ENGINE_ERROR StatusCode = 2
	// Cognitive engine expected different PayloadType from this producer.
	StatusCode_WRONG_INPUT_FORMAT StatusCode = 3
	// No cognitive engines found that match the targeted engines.
	StatusCode_NO_ENGINE_FOR_INPUT StatusCode = 4
	// This client has no tokens to send frames from this producer.
	StatusCode_NO_TOKENS StatusCode = 5
	// The server dropped the frame because it was backed up.
	StatusCode_SERVER_DROPPED_FRAME StatusCode = 6
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "SUCCESS",
		1: "UNSPECIFIED_ERROR",
		2: "ENGINE_ERROR",
		3: "WRONG_INPUT_FORMAT",
		4: "NO_ENGINE_FOR_INPUT",
		5: "NO_TOKENS",
		6: "SERVER_DROPPED_FRAME",
	}
	StatusCode_value = map[string]int32{
		"SUCCESS":              0,
		"UNSPECIFIED_ERROR":    1,
		"ENGINE_ERROR":         2,
		"WRONG_INPUT_FORMAT":   3,
		"NO_ENGINE_FOR_INPUT":  4,
		"NO_TOKENS":            5,
		"SERVER_DROPPED_FRAME": 6,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_gabriel_proto_enumTypes[1].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_gabriel_proto_enumTypes[1]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{1}
}

type InputFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payload type of this input.
	PayloadType PayloadType `protobuf:"varint,1,opt,name=payload_type,json=payloadType,proto3,enum=gabriel.PayloadType" json:"payload_type,omitempty"`
	// The payload.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*InputFrame_StringPayload
	//	*InputFrame_BytePayload
	//	*InputFrame_AnyPayload
	Payload       isInputFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputFrame) Reset() {
	*x = InputFrame{}
	mi := &file_gabriel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputFrame) ProtoMessage() {}

func (x *InputFrame) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputFrame.ProtoReflect.Descriptor instead.
func (*InputFrame) Descriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{0}
}

func (x *InputFrame) GetPayloadType() PayloadType {
	if x != nil {
		return x.PayloadType
	}
	return PayloadType_PAYLOAD_TYPE_UNSPECIFIED
}

func (x *InputFrame) GetPayload() isInputFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InputFrame) GetStringPayload() string {
	if x != nil {
		if x, ok := x.Payload.(*InputFrame_StringPayload); ok {
			return x.StringPayload
		}
	}
	return ""
}

func (x *InputFrame) GetBytePayload() []byte {
	if x != nil {
		if x, ok := x.Payload.(*InputFrame_BytePayload); ok {
			return x.BytePayload
		}
	}
	return nil
}

func (x *InputFrame) GetAnyPayload() *anypb.Any {
	if x != nil {
		if x, ok := x.Payload.(*InputFrame_AnyPayload); ok {
			return x.AnyPayload
		}
	}
	return nil
}

type isInputFrame_Payload interface {
	isInputFrame_Payload()
}

type InputFrame_StringPayload struct {
	StringPayload string `protobuf:"bytes,2,opt,name=string_payload,json=stringPayload,proto3,oneof"`
}

type InputFrame_BytePayload struct {
	BytePayload []byte `protobuf:"bytes,3,opt,name=byte_payload,json=bytePayload,proto3,oneof"`
}

type InputFrame_AnyPayload struct {
	AnyPayload *anypb.Any `protobuf:"bytes,4,opt,name=any_payload,json=anyPayload,proto3,oneof"`
}

func (*InputFrame_StringPayload) isInputFrame_Payload() {}

func (*InputFrame_BytePayload) isInputFrame_Payload() {}

func (*InputFrame_AnyPayload) isInputFrame_Payload() {}

type FromClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A monotonically increasing frame identifier.
	FrameId int64 `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// The identifier of the producer generating input.
	ProducerId string `protobuf:"bytes,2,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	// The targeted engines for this input.
	TargetEngineIds []string `protobuf:"bytes,3,rep,name=target_engine_ids,json=targetEngineIds,proto3" json:"target_engine_ids,omitempty"`
	// The data to be sent to the server.
	InputFrame *InputFrame `protobuf:"bytes,4,opt,name=input_frame,json=inputFrame,proto3" json:"input_frame,omitempty"`
	// Arbitrary information about the client.
	ClientInfo    *anypb.Any `protobuf:"bytes,5,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromClient) Reset() {
	*x = FromClient{}
	mi := &file_gabriel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromClient) ProtoMessage() {}

func (x *FromClient) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromClient.ProtoReflect.Descriptor instead.
func (*FromClient) Descriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{1}
}

func (x *FromClient) GetFrameId() int64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *FromClient) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *FromClient) GetTargetEngineIds() []string {
	if x != nil {
		return x.TargetEngineIds
	}
	return nil
}

func (x *FromClient) GetInputFrame() *InputFrame {
	if x != nil {
		return x.InputFrame
	}
	return nil
}

func (x *FromClient) GetClientInfo() *anypb.Any {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status code.
	Code StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=gabriel.StatusCode" json:"code,omitempty"`
	// Status message.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_gabriel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_SUCCESS
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Result struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Optional returned payload from the engine.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Result_StringResult
	//	*Result_BytesResult
	//	*Result_AnyResult
	Payload isResult_Payload `protobuf_oneof:"payload"`
	// The engine that produced this response.
	TargetEngineId string `protobuf:"bytes,5,opt,name=target_engine_id,json=targetEngineId,proto3" json:"target_engine_id,omitempty"`
	// The frame id that this result corresponds to.
	FrameId       int64 `protobuf:"varint,6,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_gabriel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{3}
}

func (x *Result) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Result) GetPayload() isResult_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Result) GetStringResult() string {
	if x != nil {
		if x, ok := x.Payload.(*Result_StringResult); ok {
			return x.StringResult
		}
	}
	return ""
}

func (x *Result) GetBytesResult() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Result_BytesResult); ok {
			return x.BytesResult
		}
	}
	return nil
}

func (x *Result) GetAnyResult() *anypb.Any {
	if x != nil {
		if x, ok := x.Payload.(*Result_AnyResult); ok {
			return x.AnyResult
		}
	}
	return nil
}

func (x *Result) GetTargetEngineId() string {
	if x != nil {
		return x.TargetEngineId
	}
	return ""
}

func (x *Result) GetFrameId() int64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

type isResult_Payload interface {
	isResult_Payload()
}

type Result_StringResult struct {
	StringResult string `protobuf:"bytes,2,opt,name=string_result,json=stringResult,proto3,oneof"`
}

type Result_BytesResult struct {
	BytesResult []byte `protobuf:"bytes,3,opt,name=bytes_result,json=bytesResult,proto3,oneof"`
}

type Result_AnyResult struct {
	AnyResult *anypb.Any `protobuf:"bytes,4,opt,name=any_result,json=anyResult,proto3,oneof"`
}

func (*Result_StringResult) isResult_Payload() {}

func (*Result_BytesResult) isResult_Payload() {}

func (*Result_AnyResult) isResult_Payload() {}

type ToClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*ToClient_Welcome_
	//	*ToClient_ResultWrapper_
	//	*ToClient_Control_
	MessageType   isToClient_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToClient) Reset() {
	*x = ToClient{}
	mi := &file_gabriel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToClient) ProtoMessage() {}

func (x *ToClient) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToClient.ProtoReflect.Descriptor instead.
func (*ToClient) Descriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{4}
}

func (x *ToClient) GetMessageType() isToClient_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *ToClient) GetWelcome() *ToClient_Welcome {
	if x != nil {
		if x, ok := x.MessageType.(*ToClient_Welcome_); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ToClient) GetResultWrapper() *ToClient_ResultWrapper {
	if x != nil {
		if x, ok := x.MessageType.(*ToClient_ResultWrapper_); ok {
			return x.ResultWrapper
		}
	}
	return nil
}

func (x *ToClient) GetControl() *ToClient_Control {
	if x != nil {
		if x, ok := x.MessageType.(*ToClient_Control_); ok {
			return x.Control
		}
	}
	return nil
}

type isToClient_MessageType interface {
	isToClient_MessageType()
}

type ToClient_Welcome_ struct {
	Welcome *ToClient_Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ToClient_ResultWrapper_ struct {
	ResultWrapper *ToClient_ResultWrapper `protobuf:"bytes,2,opt,name=result_wrapper,json=resultWrapper,proto3,oneof"`
}

type ToClient_Control_ struct {
	Control *ToClient_Control `protobuf:"bytes,3,opt,name=control,proto3,oneof"`
}

func (*ToClient_Welcome_) isToClient_MessageType() {}

func (*ToClient_ResultWrapper_) isToClient_MessageType() {}

func (*ToClient_Control_) isToClient_MessageType() {}

type FromStandaloneEngine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to WelcomeOrResult:
	//
	//	*FromStandaloneEngine_Welcome_
	//	*FromStandaloneEngine_Result
	WelcomeOrResult isFromStandaloneEngine_WelcomeOrResult `protobuf_oneof:"welcome_or_result"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FromStandaloneEngine) Reset() {
	*x = FromStandaloneEngine{}
	mi := &file_gabriel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromStandaloneEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromStandaloneEngine) ProtoMessage() {}

func (x *FromStandaloneEngine) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromStandaloneEngine.ProtoReflect.Descriptor instead.
func (*FromStandaloneEngine) Descriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{5}
}

func (x *FromStandaloneEngine) GetWelcomeOrResult() isFromStandaloneEngine_WelcomeOrResult {
	if x != nil {
		return x.WelcomeOrResult
	}
	return nil
}

func (x *FromStandaloneEngine) GetWelcome() *FromStandaloneEngine_Welcome {
	if x != nil {
		if x, ok := x.WelcomeOrResult.(*FromStandaloneEngine_Welcome_); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *FromStandaloneEngine) GetResult() *Result {
	if x != nil {
		if x, ok := x.WelcomeOrResult.(*FromStandaloneEngine_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isFromStandaloneEngine_WelcomeOrResult interface {
	isFromStandaloneEngine_WelcomeOrResult()
}

type FromStandaloneEngine_Welcome_ struct {
	Welcome *FromStandaloneEngine_Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type FromStandaloneEngine_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*FromStandaloneEngine_Welcome_) isFromStandaloneEngine_WelcomeOrResult() {}

func (*FromStandaloneEngine_Result) isFromStandaloneEngine_WelcomeOrResult() {}

type ToClient_Welcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of tokens each producer should get.
	NumTokensPerProducer int32 `protobuf:"varint,1,opt,name=num_tokens_per_producer,json=numTokensPerProducer,proto3" json:"num_tokens_per_producer,omitempty"`
	// The engine ids that are connected to the server.
	EngineIds     []string `protobuf:"bytes,2,rep,name=engine_ids,json=engineIds,proto3" json:"engine_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToClient_Welcome) Reset() {
	*x = ToClient_Welcome{}
	mi := &file_gabriel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToClient_Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToClient_Welcome) ProtoMessage() {}

func (x *ToClient_Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToClient_Welcome.ProtoReflect.Descriptor instead.
func (*ToClient_Welcome) Descriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ToClient_Welcome) GetNumTokensPerProducer() int32 {
	if x != nil {
		return x.NumTokensPerProducer
	}
	return 0
}

func (x *ToClient_Welcome) GetEngineIds() []string {
	if x != nil {
		return x.EngineIds
	}
	return nil
}

type ToClient_Control struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new set of engine ids connected to the server.
	EngineIds     []string `protobuf:"bytes,1,rep,name=engine_ids,json=engineIds,proto3" json:"engine_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToClient_Control) Reset() {
	*x = ToClient_Control{}
	mi := &file_gabriel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToClient_Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToClient_Control) ProtoMessage() {}

func (x *ToClient_Control) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToClient_Control.ProtoReflect.Descriptor instead.
func (*ToClient_Control) Descriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ToClient_Control) GetEngineIds() []string {
	if x != nil {
		return x.EngineIds
	}
	return nil
}

type ToClient_ResultWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The producer of the original frame; allows the client to return the
	// token correctly.
	ProducerId string `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	// Whether to replenish a client token.
	ReturnToken bool `protobuf:"varint,2,opt,name=return_token,json=returnToken,proto3" json:"return_token,omitempty"`
	// The result sent from the engine.
	Result        *Result `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToClient_ResultWrapper) Reset() {
	*x = ToClient_ResultWrapper{}
	mi := &file_gabriel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToClient_ResultWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToClient_ResultWrapper) ProtoMessage() {}

func (x *ToClient_ResultWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToClient_ResultWrapper.ProtoReflect.Descriptor instead.
func (*ToClient_ResultWrapper) Descriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{4, 2}
}

func (x *ToClient_ResultWrapper) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *ToClient_ResultWrapper) GetReturnToken() bool {
	if x != nil {
		return x.ReturnToken
	}
	return false
}

func (x *ToClient_ResultWrapper) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type FromStandaloneEngine_Welcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The engine id.
	EngineId string `protobuf:"bytes,1,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	// Whether all responses from this engine should be sent to the client,
	// even if they do not correspond to the latest input. This flag
	// determines whether stale results are sent to the client.
	AllResponsesRequired bool `protobuf:"varint,2,opt,name=all_responses_required,json=allResponsesRequired,proto3" json:"all_responses_required,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FromStandaloneEngine_Welcome) Reset() {
	*x = FromStandaloneEngine_Welcome{}
	mi := &file_gabriel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromStandaloneEngine_Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromStandaloneEngine_Welcome) ProtoMessage() {}

func (x *FromStandaloneEngine_Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromStandaloneEngine_Welcome.ProtoReflect.Descriptor instead.
func (*FromStandaloneEngine_Welcome) Descriptor() ([]byte, []int) {
	return file_gabriel_proto_rawDescGZIP(), []int{5, 0}
}

func (x *FromStandaloneEngine_Welcome) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *FromStandaloneEngine_Welcome) GetAllResponsesRequired() bool {
	if x != nil {
		return x.AllResponsesRequired
	}
	return false
}

var File_gabriel_proto protoreflect.FileDescriptor

const file_gabriel_proto_rawDesc = "" +
	"\n" +
	"\rgabriel.proto\x12\agabriel\x1a\x19google/protobuf/any.proto\"\xd7\x01\n" +
	"\n" +
	"InputFrame\x127\n" +
	"\fpayload_type\x18\x01 \x01(\x0e2\x14.gabriel.PayloadTypeR\vpayloadType\x12'\n" +
	"\x0estring_payload\x18\x02 \x01(\tH\x00R\rstringPayload\x12#\n" +
	"\fbyte_payload\x18\x03 \x01(\fH\x00R\vbytePayload\x127\n" +
	"\vany_payload\x18\x04 \x01(\v2\x14.google.protobuf.AnyH\x00R\n" +
	"anyPayloadB\t\n" +
	"\apayload\"\xe1\x01\n" +
	"\n" +
	"FromClient\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\x03R\aframeId\x12\x1f\n" +
	"\vproducer_id\x18\x02 \x01(\tR\n" +
	"producerId\x12*\n" +
	"\x11target_engine_ids\x18\x03 \x03(\tR\x0ftargetEngineIds\x124\n" +
	"\vinput_frame\x18\x04 \x01(\v2\x13.gabriel.InputFrameR\n" +
	"inputFrame\x125\n" +
	"\vclient_info\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\n" +
	"clientInfo\"K\n" +
	"\x06Status\x12'\n" +
	"\x04code\x18\x01 \x01(\x0e2\x13.gabriel.StatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x02\n" +
	"\x06Result\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.gabriel.StatusR\x06status\x12%\n" +
	"\rstring_result\x18\x02 \x01(\tH\x00R\fstringResult\x12#\n" +
	"\fbytes_result\x18\x03 \x01(\fH\x00R\vbytesResult\x125\n" +
	"\n" +
	"any_result\x18\x04 \x01(\v2\x14.google.protobuf.AnyH\x00R\tanyResult\x12(\n" +
	"\x10target_engine_id\x18\x05 \x01(\tR\x0etargetEngineId\x12\x19\n" +
	"\bframe_id\x18\x06 \x01(\x03R\aframeIdB\t\n" +
	"\apayload\"\xdb\x03\n" +
	"\bToClient\x125\n" +
	"\awelcome\x18\x01 \x01(\v2\x19.gabriel.ToClient.WelcomeH\x00R\awelcome\x12H\n" +
	"\x0eresult_wrapper\x18\x02 \x01(\v2\x1f.gabriel.ToClient.ResultWrapperH\x00R\rresultWrapper\x125\n" +
	"\acontrol\x18\x03 \x01(\v2\x19.gabriel.ToClient.ControlH\x00R\acontrol\x1a_\n" +
	"\aWelcome\x125\n" +
	"\x17num_tokens_per_producer\x18\x01 \x01(\x05R\x14numTokensPerProducer\x12\x1d\n" +
	"\n" +
	"engine_ids\x18\x02 \x03(\tR\tengineIds\x1a(\n" +
	"\aControl\x12\x1d\n" +
	"\n" +
	"engine_ids\x18\x01 \x03(\tR\tengineIds\x1a|\n" +
	"\rResultWrapper\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12!\n" +
	"\freturn_token\x18\x02 \x01(\bR\vreturnToken\x12'\n" +
	"\x06result\x18\x03 \x01(\v2\x0f.gabriel.ResultR\x06resultB\x0e\n" +
	"\fmessage_type\"\xf7\x01\n" +
	"\x14FromStandaloneEngine\x12A\n" +
	"\awelcome\x18\x01 \x01(\v2%.gabriel.FromStandaloneEngine.WelcomeH\x00R\awelcome\x12)\n" +
	"\x06result\x18\x02 \x01(\v2\x0f.gabriel.ResultH\x00R\x06result\x1a\\\n" +
	"\aWelcome\x12\x1b\n" +
	"\tengine_id\x18\x01 \x01(\tR\bengineId\x124\n" +
	"\x16all_responses_required\x18\x02 \x01(\bR\x14allResponsesRequiredB\x13\n" +
	"\x11welcome_or_result*n\n" +
	"\vPayloadType\x12\x1c\n" +
	"\x18PAYLOAD_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\t\n" +
	"\x05IMAGE\x10\x02\x12\t\n" +
	"\x05AUDIO\x10\x03\x12\t\n" +
	"\x05VIDEO\x10\x04\x12\v\n" +
	"\aCONTROL\x10\x05\x12\t\n" +
	"\x05OTHER\x10d*\x9c\x01\n" +
	"\n" +
	"StatusCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x15\n" +
	"\x11UNSPECIFIED_ERROR\x10\x01\x12\x10\n" +
	"\fENGINE_ERROR\x10\x02\x12\x16\n" +
	"\x12WRONG_INPUT_FORMAT\x10\x03\x12\x17\n" +
	"\x13NO_ENGINE_FOR_INPUT\x10\x04\x12\r\n" +
	"\tNO_TOKENS\x10\x05\x12\x18\n" +
	"\x14SERVER_DROPPED_FRAME\x10\x06B[\n" +
	"\x1bedu.cmu.cs.gabriel.protocolB\x06ProtosZ4github.com/cmusatyalab/gabriel/protocol/go;gabrielpbb\x06proto3"

var (
	file_gabriel_proto_rawDescOnce sync.Once
	file_gabriel_proto_rawDescData []byte
)

func file_gabriel_proto_rawDescGZIP() []byte {
	file_gabriel_proto_rawDescOnce.Do(func() {
		file_gabriel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gabriel_proto_rawDesc), len(file_gabriel_proto_rawDesc)))
	})
	return file_gabriel_proto_rawDescData
}

var file_gabriel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gabriel_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gabriel_proto_goTypes = []any{
	(PayloadType)(0),                     // 0: gabriel.PayloadType
	(StatusCode)(0),                      // 1: gabriel.StatusCode
	(*InputFrame)(nil),                   // 2: gabriel.InputFrame
	(*FromClient)(nil),                   // 3: gabriel.FromClient
	(*Status)(nil),                       // 4: gabriel.Status
	(*Result)(nil),                       // 5: gabriel.Result
	(*ToClient)(nil),                     // 6: gabriel.ToClient
	(*FromStandaloneEngine)(nil),         // 7: gabriel.FromStandaloneEngine
	(*ToClient_Welcome)(nil),             // 8: gabriel.ToClient.Welcome
	(*ToClient_Control)(nil),             // 9: gabriel.ToClient.Control
	(*ToClient_ResultWrapper)(nil),       // 10: gabriel.ToClient.ResultWrapper
	(*FromStandaloneEngine_Welcome)(nil), // 11: gabriel.FromStandaloneEngine.Welcome
	(*anypb.Any)(nil),                    // 12: google.protobuf.Any
}
var file_gabriel_proto_depIdxs = []int32{
	0,  // 0: gabriel.InputFrame.payload_type:type_name -> gabriel.PayloadType
	12, // 1: gabriel.InputFrame.any_payload:type_name -> google.protobuf.Any
	2,  // 2: gabriel.FromClient.input_frame:type_name -> gabriel.InputFrame
	12, // 3: gabriel.FromClient.client_info:type_name -> google.protobuf.Any
	1,  // 4: gabriel.Status.code:type_name -> gabriel.StatusCode
	4,  // 5: gabriel.Result.status:type_name -> gabriel.Status
	12, // 6: gabriel.Result.any_result:type_name -> google.protobuf.Any
	8,  // 7: gabriel.ToClient.welcome:type_name -> gabriel.ToClient.Welcome
	10, // 8: gabriel.ToClient.result_wrapper:type_name -> gabriel.ToClient.ResultWrapper
	9,  // 9: gabriel.ToClient.control:type_name -> gabriel.ToClient.Control
	11, // 10: gabriel.FromStandaloneEngine.welcome:type_name -> gabriel.FromStandaloneEngine.Welcome
	5,  // 11: gabriel.FromStandaloneEngine.result:type_name -> gabriel.Result
	5,  // 12: gabriel.ToClient.ResultWrapper.result:type_name -> gabriel.Result
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_gabriel_proto_init() }
func file_gabriel_proto_init() {
	if File_gabriel_proto != nil {
		return
	}
	file_gabriel_proto_msgTypes[0].OneofWrappers = []any{
		(*InputFrame_StringPayload)(nil),
		(*InputFrame_BytePayload)(nil),
		(*InputFrame_AnyPayload)(nil),
	}
	file_gabriel_proto_msgTypes[3].OneofWrappers = []any{
		(*Result_StringResult)(nil),
		(*Result_BytesResult)(nil),
		(*Result_AnyResult)(nil),
	}
	file_gabriel_proto_msgTypes[4].OneofWrappers = []any{
		(*ToClient_Welcome_)(nil),
		(*ToClient_ResultWrapper_)(nil),
		(*ToClient_Control_)(nil),
	}
	file_gabriel_proto_msgTypes[5].OneofWrappers = []any{
		(*FromStandaloneEngine_Welcome_)(nil),
		(*FromStandaloneEngine_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gabriel_proto_rawDesc), len(file_gabriel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gabriel_proto_goTypes,
		DependencyIndexes: file_gabriel_proto_depIdxs,
		EnumInfos:         file_gabriel_proto_enumTypes,
		MessageInfos:      file_gabriel_proto_msgTypes,
	}.Build()
	File_gabriel_proto = out.File
	file_gabriel_proto_goTypes = nil
	file_gabriel_proto_depIdxs = nil
}
