// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gabriel_protocol/v1/gabriel.proto

package gabrielpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadType int32

const (
	PayloadType_PAYLOAD_TYPE_UNSPECIFIED PayloadType = 0
	PayloadType_TEXT                     PayloadType = 1
	PayloadType_IMAGE                    PayloadType = 2
	PayloadType_AUDIO                    PayloadType = 3
	PayloadType_VIDEO                    PayloadType = 4
	PayloadType_OTHER                    PayloadType = 100
)

// Enum value maps for PayloadType.
var (
	PayloadType_name = map[int32]string{
		0:   "PAYLOAD_TYPE_UNSPECIFIED",
		1:   "TEXT",
		2:   "IMAGE",
		3:   "AUDIO",
		4:   "VIDEO",
		100: "OTHER",
	}
	PayloadType_value = map[string]int32{
		"PAYLOAD_TYPE_UNSPECIFIED": 0,
		"TEXT":                     1,
		"IMAGE":                    2,
		"AUDIO":                    3,
		"VIDEO":                    4,
		"OTHER":                    100,
	}
)

func (x PayloadType) Enum() *PayloadType {
	p := new(PayloadType)
	*p = x
	return p
}

func (x PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_gabriel_protocol_v1_gabriel_proto_enumTypes[0].Descriptor()
}

func (PayloadType) Type() protoreflect.EnumType {
	return &file_gabriel_protocol_v1_gabriel_proto_enumTypes[0]
}

func (x PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadType.Descriptor instead.
func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{0}
}

type StatusCode int32

const (
	StatusCode_STATUS_CODE_UNSPECIFIED StatusCode = 0
	// Success.
	StatusCode_SUCCESS StatusCode = 1
	// Errors whose cause is not known.
	StatusCode_UNSPECIFIED_ERROR StatusCode = 2
	// Errors that are not related to Gabriel but rather to the engine itself.
	StatusCode_ENGINE_ERROR StatusCode = 3
	// Cognitive engine expected different PayloadType from this producer.
	StatusCode_WRONG_INPUT_FORMAT StatusCode = 4
	// No cognitive engines found that match the targeted engines.
	StatusCode_NO_ENGINE_FOR_INPUT StatusCode = 5
	// This client has no tokens to send frames from this producer.
	StatusCode_NO_TOKENS StatusCode = 6
	// The server dropped the frame because it was backed up.
	StatusCode_SERVER_DROPPED_FRAME StatusCode = 7
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "STATUS_CODE_UNSPECIFIED",
		1: "SUCCESS",
		2: "UNSPECIFIED_ERROR",
		3: "ENGINE_ERROR",
		4: "WRONG_INPUT_FORMAT",
		5: "NO_ENGINE_FOR_INPUT",
		6: "NO_TOKENS",
		7: "SERVER_DROPPED_FRAME",
	}
	StatusCode_value = map[string]int32{
		"STATUS_CODE_UNSPECIFIED": 0,
		"SUCCESS":                 1,
		"UNSPECIFIED_ERROR":       2,
		"ENGINE_ERROR":            3,
		"WRONG_INPUT_FORMAT":      4,
		"NO_ENGINE_FOR_INPUT":     5,
		"NO_TOKENS":               6,
		"SERVER_DROPPED_FRAME":    7,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_gabriel_protocol_v1_gabriel_proto_enumTypes[1].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_gabriel_protocol_v1_gabriel_proto_enumTypes[1]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{1}
}

type InputFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payload type of this input.
	PayloadType PayloadType `protobuf:"varint,1,opt,name=payload_type,json=payloadType,proto3,enum=gabriel_protocol.v1.PayloadType" json:"payload_type,omitempty"`
	// The payload.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*InputFrame_StringPayload
	//	*InputFrame_BytePayload
	//	*InputFrame_AnyPayload
	Payload       isInputFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputFrame) Reset() {
	*x = InputFrame{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputFrame) ProtoMessage() {}

func (x *InputFrame) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputFrame.ProtoReflect.Descriptor instead.
func (*InputFrame) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{0}
}

func (x *InputFrame) GetPayloadType() PayloadType {
	if x != nil {
		return x.PayloadType
	}
	return PayloadType_PAYLOAD_TYPE_UNSPECIFIED
}

func (x *InputFrame) GetPayload() isInputFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InputFrame) GetStringPayload() string {
	if x != nil {
		if x, ok := x.Payload.(*InputFrame_StringPayload); ok {
			return x.StringPayload
		}
	}
	return ""
}

func (x *InputFrame) GetBytePayload() []byte {
	if x != nil {
		if x, ok := x.Payload.(*InputFrame_BytePayload); ok {
			return x.BytePayload
		}
	}
	return nil
}

func (x *InputFrame) GetAnyPayload() *anypb.Any {
	if x != nil {
		if x, ok := x.Payload.(*InputFrame_AnyPayload); ok {
			return x.AnyPayload
		}
	}
	return nil
}

type isInputFrame_Payload interface {
	isInputFrame_Payload()
}

type InputFrame_StringPayload struct {
	StringPayload string `protobuf:"bytes,2,opt,name=string_payload,json=stringPayload,proto3,oneof"`
}

type InputFrame_BytePayload struct {
	BytePayload []byte `protobuf:"bytes,3,opt,name=byte_payload,json=bytePayload,proto3,oneof"`
}

type InputFrame_AnyPayload struct {
	AnyPayload *anypb.Any `protobuf:"bytes,4,opt,name=any_payload,json=anyPayload,proto3,oneof"`
}

func (*InputFrame_StringPayload) isInputFrame_Payload() {}

func (*InputFrame_BytePayload) isInputFrame_Payload() {}

func (*InputFrame_AnyPayload) isInputFrame_Payload() {}

type FromClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*FromClient_Input_
	//	*FromClient_Registration_
	MessageType   isFromClient_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromClient) Reset() {
	*x = FromClient{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromClient) ProtoMessage() {}

func (x *FromClient) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromClient.ProtoReflect.Descriptor instead.
func (*FromClient) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{1}
}

func (x *FromClient) GetMessageType() isFromClient_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *FromClient) GetInput() *FromClient_Input {
	if x != nil {
		if x, ok := x.MessageType.(*FromClient_Input_); ok {
			return x.Input
		}
	}
	return nil
}

func (x *FromClient) GetRegistration() *FromClient_Registration {
	if x != nil {
		if x, ok := x.MessageType.(*FromClient_Registration_); ok {
			return x.Registration
		}
	}
	return nil
}

type isFromClient_MessageType interface {
	isFromClient_MessageType()
}

type FromClient_Input_ struct {
	Input *FromClient_Input `protobuf:"bytes,1,opt,name=input,proto3,oneof"`
}

type FromClient_Registration_ struct {
	// Sent immediately upon connecting, and retried until a Registered
	// response is received. Must be acknowledged before the server will accept
	// Input messages from this client.
	Registration *FromClient_Registration `protobuf:"bytes,2,opt,name=registration,proto3,oneof"`
}

func (*FromClient_Input_) isFromClient_MessageType() {}

func (*FromClient_Registration_) isFromClient_MessageType() {}

type Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status code.
	Code StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=gabriel_protocol.v1.StatusCode" json:"code,omitempty"`
	// Status message.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_STATUS_CODE_UNSPECIFIED
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Result struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Optional returned payload from the engine.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Result_StringResult
	//	*Result_BytesResult
	//	*Result_AnyResult
	Payload isResult_Payload `protobuf_oneof:"payload"`
	// The engine that produced this response.
	TargetEngineId string `protobuf:"bytes,5,opt,name=target_engine_id,json=targetEngineId,proto3" json:"target_engine_id,omitempty"`
	// The frame id that this result corresponds to.
	FrameId       int64 `protobuf:"varint,6,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{3}
}

func (x *Result) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Result) GetPayload() isResult_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Result) GetStringResult() string {
	if x != nil {
		if x, ok := x.Payload.(*Result_StringResult); ok {
			return x.StringResult
		}
	}
	return ""
}

func (x *Result) GetBytesResult() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Result_BytesResult); ok {
			return x.BytesResult
		}
	}
	return nil
}

func (x *Result) GetAnyResult() *anypb.Any {
	if x != nil {
		if x, ok := x.Payload.(*Result_AnyResult); ok {
			return x.AnyResult
		}
	}
	return nil
}

func (x *Result) GetTargetEngineId() string {
	if x != nil {
		return x.TargetEngineId
	}
	return ""
}

func (x *Result) GetFrameId() int64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

type isResult_Payload interface {
	isResult_Payload()
}

type Result_StringResult struct {
	StringResult string `protobuf:"bytes,2,opt,name=string_result,json=stringResult,proto3,oneof"`
}

type Result_BytesResult struct {
	BytesResult []byte `protobuf:"bytes,3,opt,name=bytes_result,json=bytesResult,proto3,oneof"`
}

type Result_AnyResult struct {
	AnyResult *anypb.Any `protobuf:"bytes,4,opt,name=any_result,json=anyResult,proto3,oneof"`
}

func (*Result_StringResult) isResult_Payload() {}

func (*Result_BytesResult) isResult_Payload() {}

func (*Result_AnyResult) isResult_Payload() {}

type ToClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*ToClient_Registered_
	//	*ToClient_ResultWrapper_
	//	*ToClient_EngineIdsUpdate_
	MessageType   isToClient_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToClient) Reset() {
	*x = ToClient{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToClient) ProtoMessage() {}

func (x *ToClient) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToClient.ProtoReflect.Descriptor instead.
func (*ToClient) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{4}
}

func (x *ToClient) GetMessageType() isToClient_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *ToClient) GetRegistered() *ToClient_Registered {
	if x != nil {
		if x, ok := x.MessageType.(*ToClient_Registered_); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *ToClient) GetResultWrapper() *ToClient_ResultWrapper {
	if x != nil {
		if x, ok := x.MessageType.(*ToClient_ResultWrapper_); ok {
			return x.ResultWrapper
		}
	}
	return nil
}

func (x *ToClient) GetEngineIdsUpdate() *ToClient_EngineIdsUpdate {
	if x != nil {
		if x, ok := x.MessageType.(*ToClient_EngineIdsUpdate_); ok {
			return x.EngineIdsUpdate
		}
	}
	return nil
}

type isToClient_MessageType interface {
	isToClient_MessageType()
}

type ToClient_Registered_ struct {
	// Sent in response to a client's Registration message; acknowledges
	// that registration succeeded and provides session configuration.
	Registered *ToClient_Registered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type ToClient_ResultWrapper_ struct {
	ResultWrapper *ToClient_ResultWrapper `protobuf:"bytes,2,opt,name=result_wrapper,json=resultWrapper,proto3,oneof"`
}

type ToClient_EngineIdsUpdate_ struct {
	EngineIdsUpdate *ToClient_EngineIdsUpdate `protobuf:"bytes,3,opt,name=engine_ids_update,json=engineIdsUpdate,proto3,oneof"`
}

func (*ToClient_Registered_) isToClient_MessageType() {}

func (*ToClient_ResultWrapper_) isToClient_MessageType() {}

func (*ToClient_EngineIdsUpdate_) isToClient_MessageType() {}

type FromEngine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*FromEngine_Register_
	//	*FromEngine_Result
	MessageType   isFromEngine_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromEngine) Reset() {
	*x = FromEngine{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromEngine) ProtoMessage() {}

func (x *FromEngine) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromEngine.ProtoReflect.Descriptor instead.
func (*FromEngine) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{5}
}

func (x *FromEngine) GetMessageType() isFromEngine_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *FromEngine) GetRegister() *FromEngine_Register {
	if x != nil {
		if x, ok := x.MessageType.(*FromEngine_Register_); ok {
			return x.Register
		}
	}
	return nil
}

func (x *FromEngine) GetResult() *Result {
	if x != nil {
		if x, ok := x.MessageType.(*FromEngine_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isFromEngine_MessageType interface {
	isFromEngine_MessageType()
}

type FromEngine_Register_ struct {
	Register *FromEngine_Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type FromEngine_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*FromEngine_Register_) isFromEngine_MessageType() {}

func (*FromEngine_Result) isFromEngine_MessageType() {}

type ToEngine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*ToEngine_InputFrame
	MessageType isToEngine_MessageType `protobuf_oneof:"message_type"`
	// Client-specific information registered by the producer of this input,
	// forwarded from the client's Registration message. Unset if the
	// producing client did not register any.
	ClientInfo    *anypb.Any `protobuf:"bytes,2,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToEngine) Reset() {
	*x = ToEngine{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToEngine) ProtoMessage() {}

func (x *ToEngine) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToEngine.ProtoReflect.Descriptor instead.
func (*ToEngine) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{6}
}

func (x *ToEngine) GetMessageType() isToEngine_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *ToEngine) GetInputFrame() *InputFrame {
	if x != nil {
		if x, ok := x.MessageType.(*ToEngine_InputFrame); ok {
			return x.InputFrame
		}
	}
	return nil
}

func (x *ToEngine) GetClientInfo() *anypb.Any {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type isToEngine_MessageType interface {
	isToEngine_MessageType()
}

type ToEngine_InputFrame struct {
	InputFrame *InputFrame `protobuf:"bytes,1,opt,name=input_frame,json=inputFrame,proto3,oneof"`
}

func (*ToEngine_InputFrame) isToEngine_MessageType() {}

type FromClient_Input struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A monotonically increasing frame identifier.
	FrameId int64 `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// The identifier of the producer generating input.
	ProducerId string `protobuf:"bytes,2,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	// The targeted engines for this input.
	TargetEngineIds []string `protobuf:"bytes,3,rep,name=target_engine_ids,json=targetEngineIds,proto3" json:"target_engine_ids,omitempty"`
	// The data to be sent to the server.
	InputFrame    *InputFrame `protobuf:"bytes,4,opt,name=input_frame,json=inputFrame,proto3" json:"input_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromClient_Input) Reset() {
	*x = FromClient_Input{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromClient_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromClient_Input) ProtoMessage() {}

func (x *FromClient_Input) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromClient_Input.ProtoReflect.Descriptor instead.
func (*FromClient_Input) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FromClient_Input) GetFrameId() int64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *FromClient_Input) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *FromClient_Input) GetTargetEngineIds() []string {
	if x != nil {
		return x.TargetEngineIds
	}
	return nil
}

func (x *FromClient_Input) GetInputFrame() *InputFrame {
	if x != nil {
		return x.InputFrame
	}
	return nil
}

type FromClient_Registration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arbitrary client-specific information, made available to engines
	// alongside any input the client subsequently sends.
	ClientInfo    *anypb.Any `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromClient_Registration) Reset() {
	*x = FromClient_Registration{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromClient_Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromClient_Registration) ProtoMessage() {}

func (x *FromClient_Registration) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromClient_Registration.ProtoReflect.Descriptor instead.
func (*FromClient_Registration) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{1, 1}
}

func (x *FromClient_Registration) GetClientInfo() *anypb.Any {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type ToClient_Registered struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of tokens each producer should get.
	NumTokensPerProducer int32 `protobuf:"varint,1,opt,name=num_tokens_per_producer,json=numTokensPerProducer,proto3" json:"num_tokens_per_producer,omitempty"`
	// The engine ids that are connected to the server.
	EngineIds     []string `protobuf:"bytes,2,rep,name=engine_ids,json=engineIds,proto3" json:"engine_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToClient_Registered) Reset() {
	*x = ToClient_Registered{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToClient_Registered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToClient_Registered) ProtoMessage() {}

func (x *ToClient_Registered) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToClient_Registered.ProtoReflect.Descriptor instead.
func (*ToClient_Registered) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ToClient_Registered) GetNumTokensPerProducer() int32 {
	if x != nil {
		return x.NumTokensPerProducer
	}
	return 0
}

func (x *ToClient_Registered) GetEngineIds() []string {
	if x != nil {
		return x.EngineIds
	}
	return nil
}

// Sent whenever the set of engines connected to the server changes, so
// clients can keep their view of available engine ids up to date.
type ToClient_EngineIdsUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new set of engine ids connected to the server.
	EngineIds     []string `protobuf:"bytes,1,rep,name=engine_ids,json=engineIds,proto3" json:"engine_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToClient_EngineIdsUpdate) Reset() {
	*x = ToClient_EngineIdsUpdate{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToClient_EngineIdsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToClient_EngineIdsUpdate) ProtoMessage() {}

func (x *ToClient_EngineIdsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToClient_EngineIdsUpdate.ProtoReflect.Descriptor instead.
func (*ToClient_EngineIdsUpdate) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ToClient_EngineIdsUpdate) GetEngineIds() []string {
	if x != nil {
		return x.EngineIds
	}
	return nil
}

type ToClient_ResultWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The producer of the original frame; allows the client to return the
	// token correctly.
	ProducerId string `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	// Whether to replenish a client token.
	ReturnToken bool `protobuf:"varint,2,opt,name=return_token,json=returnToken,proto3" json:"return_token,omitempty"`
	// The result sent from the engine.
	Result        *Result `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToClient_ResultWrapper) Reset() {
	*x = ToClient_ResultWrapper{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToClient_ResultWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToClient_ResultWrapper) ProtoMessage() {}

func (x *ToClient_ResultWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToClient_ResultWrapper.ProtoReflect.Descriptor instead.
func (*ToClient_ResultWrapper) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{4, 2}
}

func (x *ToClient_ResultWrapper) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *ToClient_ResultWrapper) GetReturnToken() bool {
	if x != nil {
		return x.ReturnToken
	}
	return false
}

func (x *ToClient_ResultWrapper) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type FromEngine_Register struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The engine id.
	EngineId string `protobuf:"bytes,1,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	// Whether all responses from this engine should be sent onward to the
	// producer, even if they do not correspond to the latest input. This
	// flag determines whether stale results are sent to the producer.
	AllResponsesRequired bool `protobuf:"varint,2,opt,name=all_responses_required,json=allResponsesRequired,proto3" json:"all_responses_required,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FromEngine_Register) Reset() {
	*x = FromEngine_Register{}
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromEngine_Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromEngine_Register) ProtoMessage() {}

func (x *FromEngine_Register) ProtoReflect() protoreflect.Message {
	mi := &file_gabriel_protocol_v1_gabriel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromEngine_Register.ProtoReflect.Descriptor instead.
func (*FromEngine_Register) Descriptor() ([]byte, []int) {
	return file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP(), []int{5, 0}
}

func (x *FromEngine_Register) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *FromEngine_Register) GetAllResponsesRequired() bool {
	if x != nil {
		return x.AllResponsesRequired
	}
	return false
}

var File_gabriel_protocol_v1_gabriel_proto protoreflect.FileDescriptor

const file_gabriel_protocol_v1_gabriel_proto_rawDesc = "" +
	"\n" +
	"!gabriel_protocol/v1/gabriel.proto\x12\x13gabriel_protocol.v1\x1a\x19google/protobuf/any.proto\"\xe3\x01\n" +
	"\n" +
	"InputFrame\x12C\n" +
	"\fpayload_type\x18\x01 \x01(\x0e2 .gabriel_protocol.v1.PayloadTypeR\vpayloadType\x12'\n" +
	"\x0estring_payload\x18\x02 \x01(\tH\x00R\rstringPayload\x12#\n" +
	"\fbyte_payload\x18\x03 \x01(\fH\x00R\vbytePayload\x127\n" +
	"\vany_payload\x18\x04 \x01(\v2\x14.google.protobuf.AnyH\x00R\n" +
	"anyPayloadB\t\n" +
	"\apayload\"\xaa\x03\n" +
	"\n" +
	"FromClient\x12=\n" +
	"\x05input\x18\x01 \x01(\v2%.gabriel_protocol.v1.FromClient.InputH\x00R\x05input\x12R\n" +
	"\fregistration\x18\x02 \x01(\v2,.gabriel_protocol.v1.FromClient.RegistrationH\x00R\fregistration\x1a\xb1\x01\n" +
	"\x05Input\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\x03R\aframeId\x12\x1f\n" +
	"\vproducer_id\x18\x02 \x01(\tR\n" +
	"producerId\x12*\n" +
	"\x11target_engine_ids\x18\x03 \x03(\tR\x0ftargetEngineIds\x12@\n" +
	"\vinput_frame\x18\x04 \x01(\v2\x1f.gabriel_protocol.v1.InputFrameR\n" +
	"inputFrame\x1aE\n" +
	"\fRegistration\x125\n" +
	"\vclient_info\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\n" +
	"clientInfoB\x0e\n" +
	"\fmessage_type\"W\n" +
	"\x06Status\x123\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1f.gabriel_protocol.v1.StatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x02\n" +
	"\x06Result\x123\n" +
	"\x06status\x18\x01 \x01(\v2\x1b.gabriel_protocol.v1.StatusR\x06status\x12%\n" +
	"\rstring_result\x18\x02 \x01(\tH\x00R\fstringResult\x12#\n" +
	"\fbytes_result\x18\x03 \x01(\fH\x00R\vbytesResult\x125\n" +
	"\n" +
	"any_result\x18\x04 \x01(\v2\x14.google.protobuf.AnyH\x00R\tanyResult\x12(\n" +
	"\x10target_engine_id\x18\x05 \x01(\tR\x0etargetEngineId\x12\x19\n" +
	"\bframe_id\x18\x06 \x01(\x03R\aframeIdB\t\n" +
	"\apayload\"\xba\x04\n" +
	"\bToClient\x12J\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2(.gabriel_protocol.v1.ToClient.RegisteredH\x00R\n" +
	"registered\x12T\n" +
	"\x0eresult_wrapper\x18\x02 \x01(\v2+.gabriel_protocol.v1.ToClient.ResultWrapperH\x00R\rresultWrapper\x12[\n" +
	"\x11engine_ids_update\x18\x03 \x01(\v2-.gabriel_protocol.v1.ToClient.EngineIdsUpdateH\x00R\x0fengineIdsUpdate\x1ab\n" +
	"\n" +
	"Registered\x125\n" +
	"\x17num_tokens_per_producer\x18\x01 \x01(\x05R\x14numTokensPerProducer\x12\x1d\n" +
	"\n" +
	"engine_ids\x18\x02 \x03(\tR\tengineIds\x1a0\n" +
	"\x0fEngineIdsUpdate\x12\x1d\n" +
	"\n" +
	"engine_ids\x18\x01 \x03(\tR\tengineIds\x1a\x88\x01\n" +
	"\rResultWrapper\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12!\n" +
	"\freturn_token\x18\x02 \x01(\bR\vreturnToken\x123\n" +
	"\x06result\x18\x03 \x01(\v2\x1b.gabriel_protocol.v1.ResultR\x06resultB\x0e\n" +
	"\fmessage_type\"\xfa\x01\n" +
	"\n" +
	"FromEngine\x12F\n" +
	"\bregister\x18\x01 \x01(\v2(.gabriel_protocol.v1.FromEngine.RegisterH\x00R\bregister\x125\n" +
	"\x06result\x18\x02 \x01(\v2\x1b.gabriel_protocol.v1.ResultH\x00R\x06result\x1a]\n" +
	"\bRegister\x12\x1b\n" +
	"\tengine_id\x18\x01 \x01(\tR\bengineId\x124\n" +
	"\x16all_responses_required\x18\x02 \x01(\bR\x14allResponsesRequiredB\x0e\n" +
	"\fmessage_type\"\x95\x01\n" +
	"\bToEngine\x12B\n" +
	"\vinput_frame\x18\x01 \x01(\v2\x1f.gabriel_protocol.v1.InputFrameH\x00R\n" +
	"inputFrame\x125\n" +
	"\vclient_info\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\n" +
	"clientInfoB\x0e\n" +
	"\fmessage_type*a\n" +
	"\vPayloadType\x12\x1c\n" +
	"\x18PAYLOAD_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\t\n" +
	"\x05IMAGE\x10\x02\x12\t\n" +
	"\x05AUDIO\x10\x03\x12\t\n" +
	"\x05VIDEO\x10\x04\x12\t\n" +
	"\x05OTHER\x10d*\xb9\x01\n" +
	"\n" +
	"StatusCode\x12\x1b\n" +
	"\x17STATUS_CODE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\x15\n" +
	"\x11UNSPECIFIED_ERROR\x10\x02\x12\x10\n" +
	"\fENGINE_ERROR\x10\x03\x12\x16\n" +
	"\x12WRONG_INPUT_FORMAT\x10\x04\x12\x17\n" +
	"\x13NO_ENGINE_FOR_INPUT\x10\x05\x12\r\n" +
	"\tNO_TOKENS\x10\x06\x12\x18\n" +
	"\x14SERVER_DROPPED_FRAME\x10\a2k\n" +
	"\x14GabrielClientService\x12S\n" +
	"\rClientSession\x12\x1f.gabriel_protocol.v1.FromClient\x1a\x1d.gabriel_protocol.v1.ToClient(\x010\x012k\n" +
	"\x14GabrielEngineService\x12S\n" +
	"\rEngineSession\x12\x1f.gabriel_protocol.v1.FromEngine\x1a\x1d.gabriel_protocol.v1.ToEngine(\x010\x01B6Z4github.com/cmusatyalab/gabriel/protocol/go;gabrielpbb\x06proto3"

var (
	file_gabriel_protocol_v1_gabriel_proto_rawDescOnce sync.Once
	file_gabriel_protocol_v1_gabriel_proto_rawDescData []byte
)

func file_gabriel_protocol_v1_gabriel_proto_rawDescGZIP() []byte {
	file_gabriel_protocol_v1_gabriel_proto_rawDescOnce.Do(func() {
		file_gabriel_protocol_v1_gabriel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gabriel_protocol_v1_gabriel_proto_rawDesc), len(file_gabriel_protocol_v1_gabriel_proto_rawDesc)))
	})
	return file_gabriel_protocol_v1_gabriel_proto_rawDescData
}

var file_gabriel_protocol_v1_gabriel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gabriel_protocol_v1_gabriel_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gabriel_protocol_v1_gabriel_proto_goTypes = []any{
	(PayloadType)(0),                 // 0: gabriel_protocol.v1.PayloadType
	(StatusCode)(0),                  // 1: gabriel_protocol.v1.StatusCode
	(*InputFrame)(nil),               // 2: gabriel_protocol.v1.InputFrame
	(*FromClient)(nil),               // 3: gabriel_protocol.v1.FromClient
	(*Status)(nil),                   // 4: gabriel_protocol.v1.Status
	(*Result)(nil),                   // 5: gabriel_protocol.v1.Result
	(*ToClient)(nil),                 // 6: gabriel_protocol.v1.ToClient
	(*FromEngine)(nil),               // 7: gabriel_protocol.v1.FromEngine
	(*ToEngine)(nil),                 // 8: gabriel_protocol.v1.ToEngine
	(*FromClient_Input)(nil),         // 9: gabriel_protocol.v1.FromClient.Input
	(*FromClient_Registration)(nil),  // 10: gabriel_protocol.v1.FromClient.Registration
	(*ToClient_Registered)(nil),      // 11: gabriel_protocol.v1.ToClient.Registered
	(*ToClient_EngineIdsUpdate)(nil), // 12: gabriel_protocol.v1.ToClient.EngineIdsUpdate
	(*ToClient_ResultWrapper)(nil),   // 13: gabriel_protocol.v1.ToClient.ResultWrapper
	(*FromEngine_Register)(nil),      // 14: gabriel_protocol.v1.FromEngine.Register
	(*anypb.Any)(nil),                // 15: google.protobuf.Any
}
var file_gabriel_protocol_v1_gabriel_proto_depIdxs = []int32{
	0,  // 0: gabriel_protocol.v1.InputFrame.payload_type:type_name -> gabriel_protocol.v1.PayloadType
	15, // 1: gabriel_protocol.v1.InputFrame.any_payload:type_name -> google.protobuf.Any
	9,  // 2: gabriel_protocol.v1.FromClient.input:type_name -> gabriel_protocol.v1.FromClient.Input
	10, // 3: gabriel_protocol.v1.FromClient.registration:type_name -> gabriel_protocol.v1.FromClient.Registration
	1,  // 4: gabriel_protocol.v1.Status.code:type_name -> gabriel_protocol.v1.StatusCode
	4,  // 5: gabriel_protocol.v1.Result.status:type_name -> gabriel_protocol.v1.Status
	15, // 6: gabriel_protocol.v1.Result.any_result:type_name -> google.protobuf.Any
	11, // 7: gabriel_protocol.v1.ToClient.registered:type_name -> gabriel_protocol.v1.ToClient.Registered
	13, // 8: gabriel_protocol.v1.ToClient.result_wrapper:type_name -> gabriel_protocol.v1.ToClient.ResultWrapper
	12, // 9: gabriel_protocol.v1.ToClient.engine_ids_update:type_name -> gabriel_protocol.v1.ToClient.EngineIdsUpdate
	14, // 10: gabriel_protocol.v1.FromEngine.register:type_name -> gabriel_protocol.v1.FromEngine.Register
	5,  // 11: gabriel_protocol.v1.FromEngine.result:type_name -> gabriel_protocol.v1.Result
	2,  // 12: gabriel_protocol.v1.ToEngine.input_frame:type_name -> gabriel_protocol.v1.InputFrame
	15, // 13: gabriel_protocol.v1.ToEngine.client_info:type_name -> google.protobuf.Any
	2,  // 14: gabriel_protocol.v1.FromClient.Input.input_frame:type_name -> gabriel_protocol.v1.InputFrame
	15, // 15: gabriel_protocol.v1.FromClient.Registration.client_info:type_name -> google.protobuf.Any
	5,  // 16: gabriel_protocol.v1.ToClient.ResultWrapper.result:type_name -> gabriel_protocol.v1.Result
	3,  // 17: gabriel_protocol.v1.GabrielClientService.ClientSession:input_type -> gabriel_protocol.v1.FromClient
	7,  // 18: gabriel_protocol.v1.GabrielEngineService.EngineSession:input_type -> gabriel_protocol.v1.FromEngine
	6,  // 19: gabriel_protocol.v1.GabrielClientService.ClientSession:output_type -> gabriel_protocol.v1.ToClient
	8,  // 20: gabriel_protocol.v1.GabrielEngineService.EngineSession:output_type -> gabriel_protocol.v1.ToEngine
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_gabriel_protocol_v1_gabriel_proto_init() }
func file_gabriel_protocol_v1_gabriel_proto_init() {
	if File_gabriel_protocol_v1_gabriel_proto != nil {
		return
	}
	file_gabriel_protocol_v1_gabriel_proto_msgTypes[0].OneofWrappers = []any{
		(*InputFrame_StringPayload)(nil),
		(*InputFrame_BytePayload)(nil),
		(*InputFrame_AnyPayload)(nil),
	}
	file_gabriel_protocol_v1_gabriel_proto_msgTypes[1].OneofWrappers = []any{
		(*FromClient_Input_)(nil),
		(*FromClient_Registration_)(nil),
	}
	file_gabriel_protocol_v1_gabriel_proto_msgTypes[3].OneofWrappers = []any{
		(*Result_StringResult)(nil),
		(*Result_BytesResult)(nil),
		(*Result_AnyResult)(nil),
	}
	file_gabriel_protocol_v1_gabriel_proto_msgTypes[4].OneofWrappers = []any{
		(*ToClient_Registered_)(nil),
		(*ToClient_ResultWrapper_)(nil),
		(*ToClient_EngineIdsUpdate_)(nil),
	}
	file_gabriel_protocol_v1_gabriel_proto_msgTypes[5].OneofWrappers = []any{
		(*FromEngine_Register_)(nil),
		(*FromEngine_Result)(nil),
	}
	file_gabriel_protocol_v1_gabriel_proto_msgTypes[6].OneofWrappers = []any{
		(*ToEngine_InputFrame)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gabriel_protocol_v1_gabriel_proto_rawDesc), len(file_gabriel_protocol_v1_gabriel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gabriel_protocol_v1_gabriel_proto_goTypes,
		DependencyIndexes: file_gabriel_protocol_v1_gabriel_proto_depIdxs,
		EnumInfos:         file_gabriel_protocol_v1_gabriel_proto_enumTypes,
		MessageInfos:      file_gabriel_protocol_v1_gabriel_proto_msgTypes,
	}.Build()
	File_gabriel_protocol_v1_gabriel_proto = out.File
	file_gabriel_protocol_v1_gabriel_proto_goTypes = nil
	file_gabriel_protocol_v1_gabriel_proto_depIdxs = nil
}
