# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Greeting(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Greeting()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGreeting(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Greeting
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Greeting
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Greeting
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GreetingStart(builder): builder.StartObject(2)
def Start(builder):
    return GreetingStart(builder)
def GreetingAddId(builder, id): builder.PrependInt32Slot(0, id, 0)
def AddId(builder, id):
    return GreetingAddId(builder, id)
def GreetingAddMessage(builder, message): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)
def AddMessage(builder, message):
    return GreetingAddMessage(builder, message)
def GreetingEnd(builder): return builder.EndObject()
def End(builder):
    return GreetingEnd(builder)