#ifndef GABRIEL_H
#define GABRIEL_H

/* Generated by cbindgen from rust/src/ffi.rs. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum length of a flow name.
 */
#define MAX_FLOW_NAME 64

/**
 * Status code returned by every C ABI function.
 */
typedef enum {
  GABRIEL_STATUS_T_OK = 0,
  GABRIEL_STATUS_T_ERR_INVALID,
  GABRIEL_STATUS_T_ERR_SIZE_EXCEEDED,
  GABRIEL_STATUS_T_ERR_AGAIN,
  GABRIEL_STATUS_T_ERR_INTERNAL,
} gabriel_status_t;

/**
 * Bridges local producers to a remote server.
 */
typedef struct gabriel_client_t gabriel_client_t;

/**
 * Processes inputs and replies with results of at most `max_result_size` bytes.
 */
typedef struct gabriel_engine_t gabriel_engine_t;

/**
 * Publishes inputs. An input is written in place into a loaned shared memory buffer
 * ([`Producer::new_input`]) and then sent ([`Producer::publish_input`]).
 */
typedef struct gabriel_producer_t gabriel_producer_t;

/**
 * Dispatches inputs to a dynamic set of engines.
 */
typedef struct gabriel_server_t gabriel_server_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * # Safety
 * String arguments must be NUL-terminated; `producer` must be valid for writes.
 */
gabriel_status_t gabriel_producer_create(const char *name,
                                         size_t max_input_size,
                                         gabriel_producer_t **producer);

/**
 * # Safety
 * `producer` must be null or a live handle that is not used afterwards.
 */
gabriel_status_t gabriel_producer_destroy(gabriel_producer_t *producer);

/**
 * # Safety
 * `p` must be a live handle; `buf` must be valid for writes.
 */
gabriel_status_t gabriel_producer_new_input(gabriel_producer_t *p, uint8_t **buf);

/**
 * # Safety
 * `p` must be a live handle; `flow` must be NUL-terminated.
 */
gabriel_status_t gabriel_producer_publish_input(gabriel_producer_t *p,
                                                size_t len,
                                                const char *flow);

/**
 * # Safety
 * String arguments must be NUL-terminated; `client` must be valid for writes.
 */
gabriel_status_t gabriel_client_create(const char *name,
                                       const char *local_server,
                                       const char *remote_server_addr,
                                       gabriel_client_t **client);

/**
 * # Safety
 * `client` must be null or a live handle that is not used afterwards.
 */
gabriel_status_t gabriel_client_destroy(gabriel_client_t *client);

/**
 * # Safety
 * `name` must be NUL-terminated; `client` must be a live handle.
 */
gabriel_status_t gabriel_client_add_producer(const char *name, gabriel_client_t *client);

/**
 * # Safety
 * `name` must be NUL-terminated; `client` must be a live handle.
 */
gabriel_status_t gabriel_client_remove_producer(const char *name, gabriel_client_t *client);

/**
 * # Safety
 * String arguments must be NUL-terminated; `client` must be a live handle.
 */
gabriel_status_t gabriel_client_add_flow(const char *name,
                                         const char *spec,
                                         gabriel_client_t *client);

/**
 * # Safety
 * `name` must be NUL-terminated; `client` must be a live handle.
 */
gabriel_status_t gabriel_client_remove_flow(const char *name, gabriel_client_t *client);

/**
 * # Safety
 * String arguments must be NUL-terminated; `server` must be valid for writes.
 */
gabriel_status_t gabriel_server_create(const char *name,
                                       const char *bind_addr,
                                       gabriel_server_t **server);

/**
 * # Safety
 * `server` must be null or a live handle that is not used afterwards.
 */
gabriel_status_t gabriel_server_destroy(gabriel_server_t *server);

/**
 * # Safety
 * `name` must be NUL-terminated; `server` must be a live handle.
 */
gabriel_status_t gabriel_server_add_engine(const char *name, gabriel_server_t *server);

/**
 * # Safety
 * `name` must be NUL-terminated; `server` must be a live handle.
 */
gabriel_status_t gabriel_server_remove_engine(const char *name, gabriel_server_t *server);

/**
 * # Safety
 * String arguments must be NUL-terminated; `engine` must be valid for writes.
 */
gabriel_status_t gabriel_engine_create(const char *name,
                                       size_t max_result_size,
                                       gabriel_engine_t **engine);

/**
 * # Safety
 * `engine` must be null or a live handle that is not used afterwards.
 */
gabriel_status_t gabriel_engine_destroy(gabriel_engine_t *engine);

/**
 * Polls for the next input. `*buf`, `*len` and `*producer` stay valid until
 * `gabriel_input_release`. Returns `ERR_AGAIN` if nothing is available.
 *
 * # Safety
 * `engine` must be a live handle; the out-pointers must be valid for writes.
 */
gabriel_status_t gabriel_input_poll(gabriel_engine_t *engine,
                                    const uint8_t **buf,
                                    size_t *len,
                                    const char **producer);

/**
 * # Safety
 * `engine` must be a live handle.
 */
gabriel_status_t gabriel_input_release(gabriel_engine_t *engine);

/**
 * # Safety
 * `engine` must be a live handle; `producer` must be NUL-terminated; `buf`
 * must point to `len` readable bytes (or be null when `len` is 0).
 */
gabriel_status_t gabriel_publish_result(gabriel_engine_t *engine,
                                        const char *producer,
                                        uint8_t *buf,
                                        size_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GABRIEL_H */
