// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: greeting
#ifndef GRPC_greeting__INCLUDED
#define GRPC_greeting__INCLUDED

#include "greeting_generated.h"
#include "flatbuffers/grpc.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace fbs {

class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "fbs.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Greet(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, flatbuffers::grpc::Message<Greeting>* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<Greeting>>> AsyncGreet(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<Greeting>>>(AsyncGreetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<Greeting>>> PrepareAsyncGreet(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<Greeting>>>(PrepareAsyncGreetRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<Greeting>>* AsyncGreetRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<Greeting>>* PrepareAsyncGreetRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Greet(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, flatbuffers::grpc::Message<Greeting>* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<Greeting>>> AsyncGreet(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<Greeting>>>(AsyncGreetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<Greeting>>> PrepareAsyncGreet(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<Greeting>>>(PrepareAsyncGreetRaw(context, request, cq));
    }
  
   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<Greeting>>* AsyncGreetRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<Greeting>>* PrepareAsyncGreetRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Greet_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
  
  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Greet(::grpc::ServerContext* context, const flatbuffers::grpc::Message<Greeting>* request, flatbuffers::grpc::Message<Greeting>* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Greet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithAsyncMethod_Greet() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Greet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Greet(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<Greeting>* /*request*/, flatbuffers::grpc::Message<Greeting>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGreet(::grpc::ServerContext* context, flatbuffers::grpc::Message<Greeting>* request, ::grpc::ServerAsyncResponseWriter< flatbuffers::grpc::Message<Greeting>>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef   WithAsyncMethod_Greet<  Service   >   AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Greet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithGenericMethod_Greet() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Greet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Greet(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<Greeting>* /*request*/, flatbuffers::grpc::Message<Greeting>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Greet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithStreamedUnaryMethod_Greet() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< flatbuffers::grpc::Message<Greeting>, flatbuffers::grpc::Message<Greeting>>(std::bind(&WithStreamedUnaryMethod_Greet<BaseClass>::StreamedGreet, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Greet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Greet(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<Greeting>* /*request*/, flatbuffers::grpc::Message<Greeting>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGreet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< flatbuffers::grpc::Message<Greeting>,flatbuffers::grpc::Message<Greeting>>* server_unary_streamer) = 0;
  };
  typedef   WithStreamedUnaryMethod_Greet<  Service   >   StreamedUnaryService;
  typedef   Service   SplitStreamedService;
  typedef   WithStreamedUnaryMethod_Greet<  Service   >   StreamedService;
};

}  // namespace fbs


#endif  // GRPC_greeting__INCLUDED
