// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GREETING_FBS_H_
#define FLATBUFFERS_GENERATED_GREETING_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

namespace fbs {

struct Greeting;
struct GreetingBuilder;

struct Greeting FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef GreetingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_MESSAGE = 6
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const flatbuffers::String *message() const {
    return GetPointer<const flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
};

struct GreetingBuilder {
  typedef Greeting Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(Greeting::VT_ID, id, 0);
  }
  void add_message(flatbuffers::Offset<flatbuffers::String> message) {
    fbb_.AddOffset(Greeting::VT_MESSAGE, message);
  }
  explicit GreetingBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Greeting> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Greeting>(end);
    return o;
  }
};

inline flatbuffers::Offset<Greeting> CreateGreeting(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    flatbuffers::Offset<flatbuffers::String> message = 0) {
  GreetingBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<Greeting> CreateGreetingDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return fbs::CreateGreeting(
      _fbb,
      id,
      message__);
}

inline const fbs::Greeting *GetGreeting(const void *buf) {
  return flatbuffers::GetRoot<fbs::Greeting>(buf);
}

inline const fbs::Greeting *GetSizePrefixedGreeting(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<fbs::Greeting>(buf);
}

inline bool VerifyGreetingBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fbs::Greeting>(nullptr);
}

inline bool VerifySizePrefixedGreetingBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fbs::Greeting>(nullptr);
}

inline void FinishGreetingBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::Greeting> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGreetingBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::Greeting> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_GREETING_FBS_H_
