// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: greeting

#include "greeting_generated.h"
#include "greeting.grpc.fb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace fbs {

static const char* Greeter_method_names[] = {
  "/fbs.Greeter/Greet",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& /*options*/) {
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel)  , rpcmethod_Greet_(Greeter_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}
  
::grpc::Status Greeter::Stub::Greet(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, flatbuffers::grpc::Message<Greeting>* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Greet_, context, request, response);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<Greeting>>* Greeter::Stub::AsyncGreetRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<Greeting>>::Create(channel_.get(), cq, rpcmethod_Greet_, context, request, true);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<Greeting>>* Greeter::Stub::PrepareAsyncGreetRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<Greeting>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<Greeting>>::Create(channel_.get(), cq, rpcmethod_Greet_, context, request, false);
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, flatbuffers::grpc::Message<Greeting>, flatbuffers::grpc::Message<Greeting>>(
          std::mem_fn(&Greeter::Service::Greet), this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::Greet(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<Greeting>* /*request*/, flatbuffers::grpc::Message<Greeting>* /*response*/) {
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fbs

