"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PayloadType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PayloadTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PayloadType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PAYLOAD_TYPE_UNSPECIFIED: _PayloadType.ValueType  # 0
    TEXT: _PayloadType.ValueType  # 1
    IMAGE: _PayloadType.ValueType  # 2
    AUDIO: _PayloadType.ValueType  # 3
    VIDEO: _PayloadType.ValueType  # 4
    CONTROL: _PayloadType.ValueType  # 5
    OTHER: _PayloadType.ValueType  # 100

class PayloadType(_PayloadType, metaclass=_PayloadTypeEnumTypeWrapper): ...

PAYLOAD_TYPE_UNSPECIFIED: PayloadType.ValueType  # 0
TEXT: PayloadType.ValueType  # 1
IMAGE: PayloadType.ValueType  # 2
AUDIO: PayloadType.ValueType  # 3
VIDEO: PayloadType.ValueType  # 4
CONTROL: PayloadType.ValueType  # 5
OTHER: PayloadType.ValueType  # 100
global___PayloadType = PayloadType

class _StatusCode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StatusCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StatusCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SUCCESS: _StatusCode.ValueType  # 0
    UNSPECIFIED_ERROR: _StatusCode.ValueType  # 1
    ENGINE_ERROR: _StatusCode.ValueType  # 2
    """Errors that are not related to Gabriel but rather to the engine
    itself.
    """
    WRONG_INPUT_FORMAT: _StatusCode.ValueType  # 3
    """Cognitive engine expected different PayloadType from this source."""
    NO_ENGINE_FOR_INPUT: _StatusCode.ValueType  # 4
    """No cognitive engines"""
    NO_TOKENS: _StatusCode.ValueType  # 5
    """This client has no tokens to send frames from this producer."""
    SERVER_DROPPED_FRAME: _StatusCode.ValueType  # 6
    """The server dropped the frame because it was backed up."""

class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper): ...

SUCCESS: StatusCode.ValueType  # 0
UNSPECIFIED_ERROR: StatusCode.ValueType  # 1
ENGINE_ERROR: StatusCode.ValueType  # 2
"""Errors that are not related to Gabriel but rather to the engine
itself.
"""
WRONG_INPUT_FORMAT: StatusCode.ValueType  # 3
"""Cognitive engine expected different PayloadType from this source."""
NO_ENGINE_FOR_INPUT: StatusCode.ValueType  # 4
"""No cognitive engines"""
NO_TOKENS: StatusCode.ValueType  # 5
"""This client has no tokens to send frames from this producer."""
SERVER_DROPPED_FRAME: StatusCode.ValueType  # 6
"""The server dropped the frame because it was backed up."""
global___StatusCode = StatusCode

@typing.final
class InputFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYLOAD_TYPE_FIELD_NUMBER: builtins.int
    STRING_PAYLOAD_FIELD_NUMBER: builtins.int
    BYTE_PAYLOAD_FIELD_NUMBER: builtins.int
    ANY_PAYLOAD_FIELD_NUMBER: builtins.int
    payload_type: global___PayloadType.ValueType
    string_payload: builtins.str
    byte_payload: builtins.bytes
    @property
    def any_payload(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        payload_type: global___PayloadType.ValueType = ...,
        string_payload: builtins.str = ...,
        byte_payload: builtins.bytes = ...,
        any_payload: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["any_payload", b"any_payload", "byte_payload", b"byte_payload", "payload", b"payload", "string_payload", b"string_payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["any_payload", b"any_payload", "byte_payload", b"byte_payload", "payload", b"payload", "payload_type", b"payload_type", "string_payload", b"string_payload"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["string_payload", "byte_payload", "any_payload"] | None: ...

global___InputFrame = InputFrame

@typing.final
class FromClient(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRAME_ID_FIELD_NUMBER: builtins.int
    PRODUCER_ID_FIELD_NUMBER: builtins.int
    TARGET_ENGINE_IDS_FIELD_NUMBER: builtins.int
    INPUT_FRAME_FIELD_NUMBER: builtins.int
    frame_id: builtins.int
    """A monotonically increasing frame identifier."""
    producer_id: builtins.str
    """The identifier of the producer producing input."""
    @property
    def target_engine_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """The targeted engines for this input."""

    @property
    def input_frame(self) -> global___InputFrame:
        """The data to be sent to the server."""

    def __init__(
        self,
        *,
        frame_id: builtins.int = ...,
        producer_id: builtins.str = ...,
        target_engine_ids: collections.abc.Iterable[builtins.str] | None = ...,
        input_frame: global___InputFrame | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["input_frame", b"input_frame"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["frame_id", b"frame_id", "input_frame", b"input_frame", "producer_id", b"producer_id", "target_engine_ids", b"target_engine_ids"]) -> None: ...

global___FromClient = FromClient

@typing.final
class ResultStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_CODE_FIELD_NUMBER: builtins.int
    STATUS_MSG_FIELD_NUMBER: builtins.int
    status_code: global___StatusCode.ValueType
    status_msg: builtins.str
    def __init__(
        self,
        *,
        status_code: global___StatusCode.ValueType = ...,
        status_msg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status_code", b"status_code", "status_msg", b"status_msg"]) -> None: ...

global___ResultStatus = ResultStatus

@typing.final
class Result(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_STATUS_FIELD_NUMBER: builtins.int
    STRING_RESULT_FIELD_NUMBER: builtins.int
    BYTES_RESULT_FIELD_NUMBER: builtins.int
    ANY_RESULT_FIELD_NUMBER: builtins.int
    TARGET_ENGINE_ID_FIELD_NUMBER: builtins.int
    FRAME_ID_FIELD_NUMBER: builtins.int
    string_result: builtins.str
    bytes_result: builtins.bytes
    target_engine_id: builtins.str
    """The engine that produced this response."""
    frame_id: builtins.int
    """The frame id that this result corresponds to."""
    @property
    def result_status(self) -> global___ResultStatus: ...
    @property
    def any_result(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        result_status: global___ResultStatus | None = ...,
        string_result: builtins.str = ...,
        bytes_result: builtins.bytes = ...,
        any_result: google.protobuf.any_pb2.Any | None = ...,
        target_engine_id: builtins.str = ...,
        frame_id: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["any_result", b"any_result", "bytes_result", b"bytes_result", "result", b"result", "result_status", b"result_status", "string_result", b"string_result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["any_result", b"any_result", "bytes_result", b"bytes_result", "frame_id", b"frame_id", "result", b"result", "result_status", b"result_status", "string_result", b"string_result", "target_engine_id", b"target_engine_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["result", b"result"]) -> typing.Literal["string_result", "bytes_result", "any_result"] | None: ...

global___Result = Result

@typing.final
class ToClient(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Welcome(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NUM_TOKENS_PER_SOURCE_FIELD_NUMBER: builtins.int
        ENGINE_IDS_FIELD_NUMBER: builtins.int
        num_tokens_per_source: builtins.int
        @property
        def engine_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            num_tokens_per_source: builtins.int = ...,
            engine_ids: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["engine_ids", b"engine_ids", "num_tokens_per_source", b"num_tokens_per_source"]) -> None: ...

    @typing.final
    class Control(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ENGINE_IDS_FIELD_NUMBER: builtins.int
        @property
        def engine_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            engine_ids: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["engine_ids", b"engine_ids"]) -> None: ...

    @typing.final
    class ResultWrapper(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PRODUCER_ID_FIELD_NUMBER: builtins.int
        RETURN_TOKEN_FIELD_NUMBER: builtins.int
        RESULT_FIELD_NUMBER: builtins.int
        producer_id: builtins.str
        """The producer of the original frame; allows the client to return the
        token correctly.
        """
        return_token: builtins.bool
        """Whether to replenish a client token."""
        @property
        def result(self) -> global___Result:
            """The result sent from the engine."""

        def __init__(
            self,
            *,
            producer_id: builtins.str = ...,
            return_token: builtins.bool = ...,
            result: global___Result | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["result", b"result"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["producer_id", b"producer_id", "result", b"result", "return_token", b"return_token"]) -> None: ...

    WELCOME_FIELD_NUMBER: builtins.int
    RESULT_WRAPPER_FIELD_NUMBER: builtins.int
    CONTROL_FIELD_NUMBER: builtins.int
    @property
    def welcome(self) -> global___ToClient.Welcome: ...
    @property
    def result_wrapper(self) -> global___ToClient.ResultWrapper: ...
    @property
    def control(self) -> global___ToClient.Control: ...
    def __init__(
        self,
        *,
        welcome: global___ToClient.Welcome | None = ...,
        result_wrapper: global___ToClient.ResultWrapper | None = ...,
        control: global___ToClient.Control | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["control", b"control", "message_type", b"message_type", "result_wrapper", b"result_wrapper", "welcome", b"welcome"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["control", b"control", "message_type", b"message_type", "result_wrapper", b"result_wrapper", "welcome", b"welcome"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["message_type", b"message_type"]) -> typing.Literal["welcome", "result_wrapper", "control"] | None: ...

global___ToClient = ToClient

@typing.final
class FromStandaloneEngine(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Welcome(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ENGINE_NAME_FIELD_NUMBER: builtins.int
        ALL_RESPONSES_REQUIRED_FIELD_NUMBER: builtins.int
        engine_name: builtins.str
        all_responses_required: builtins.bool
        def __init__(
            self,
            *,
            engine_name: builtins.str = ...,
            all_responses_required: builtins.bool = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["all_responses_required", b"all_responses_required", "engine_name", b"engine_name"]) -> None: ...

    WELCOME_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    @property
    def welcome(self) -> global___FromStandaloneEngine.Welcome: ...
    @property
    def result(self) -> global___Result: ...
    def __init__(
        self,
        *,
        welcome: global___FromStandaloneEngine.Welcome | None = ...,
        result: global___Result | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["result", b"result", "welcome", b"welcome", "welcome_or_result", b"welcome_or_result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["result", b"result", "welcome", b"welcome", "welcome_or_result", b"welcome_or_result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["welcome_or_result", b"welcome_or_result"]) -> typing.Literal["welcome", "result"] | None: ...

global___FromStandaloneEngine = FromStandaloneEngine
