# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gabriel_protocol import gabriel_pb2 as gabriel__protocol_dot_gabriel__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gabriel_protocol/gabriel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GabrielClientServiceStub:
    """gRPC service implemented by a Gabriel server, used by clients.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientSession = channel.stream_stream(
                '/gabriel.GabrielClientService/ClientSession',
                request_serializer=gabriel__protocol_dot_gabriel__pb2.FromClient.SerializeToString,
                response_deserializer=gabriel__protocol_dot_gabriel__pb2.ToClient.FromString,
                _registered_method=True)


class GabrielClientServiceServicer:
    """gRPC service implemented by a Gabriel server, used by clients.
    """

    def ClientSession(self, request_iterator, context):
        """Start a new session with a Gabriel server as a client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GabrielClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientSession': grpc.stream_stream_rpc_method_handler(
                    servicer.ClientSession,
                    request_deserializer=gabriel__protocol_dot_gabriel__pb2.FromClient.FromString,
                    response_serializer=gabriel__protocol_dot_gabriel__pb2.ToClient.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gabriel.GabrielClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gabriel.GabrielClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GabrielClientService:
    """gRPC service implemented by a Gabriel server, used by clients.
    """

    @staticmethod
    def ClientSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gabriel.GabrielClientService/ClientSession',
            gabriel__protocol_dot_gabriel__pb2.FromClient.SerializeToString,
            gabriel__protocol_dot_gabriel__pb2.ToClient.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GabrielEngineServiceStub:
    """gRPC service implemented by a Gabriel server, used by cognitive engines.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EngineSession = channel.stream_stream(
                '/gabriel.GabrielEngineService/EngineSession',
                request_serializer=gabriel__protocol_dot_gabriel__pb2.FromEngine.SerializeToString,
                response_deserializer=gabriel__protocol_dot_gabriel__pb2.ToEngine.FromString,
                _registered_method=True)


class GabrielEngineServiceServicer:
    """gRPC service implemented by a Gabriel server, used by cognitive engines.
    """

    def EngineSession(self, request_iterator, context):
        """Start a new session with a Gabriel server as a cognitive engine.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GabrielEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EngineSession': grpc.stream_stream_rpc_method_handler(
                    servicer.EngineSession,
                    request_deserializer=gabriel__protocol_dot_gabriel__pb2.FromEngine.FromString,
                    response_serializer=gabriel__protocol_dot_gabriel__pb2.ToEngine.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gabriel.GabrielEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gabriel.GabrielEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GabrielEngineService:
    """gRPC service implemented by a Gabriel server, used by cognitive engines.
    """

    @staticmethod
    def EngineSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gabriel.GabrielEngineService/EngineSession',
            gabriel__protocol_dot_gabriel__pb2.FromEngine.SerializeToString,
            gabriel__protocol_dot_gabriel__pb2.ToEngine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
