name: Build and push Gabriel server

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
    paths:
      - 'server/**'
      - 'protocol/python/**'
jobs:
  build-and-push:
    uses: ./.github/workflows/deploy-docker-img.yml
    with:
      name: gabriel-server
      dockerfile: server/Dockerfile
      ctx: server
      build_contexts: protocol=protocol/python
      free_disk_space: true
    secrets: inherit
