# .github/workflows/tests.yml
name: Run integration test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e python-client
          pip install -e server
          pip install -e protocol/python
          pip install pytest
          pip install pytest-asyncio
          pip install pre-commit
          pip install prometheus-client

      - name: Run pre-commit hooks
        run: |
          pre-commit install
          pre-commit run --all-files

      - name: Run pytest
        run: pytest tests/integration --log-cli-level=INFO
