# .github/workflows/publish-gabriel-client.yml
name: Publish gabriel-client to PyPI

on:
  push:
    tags:
      - "python-client/v*"

jobs:
  publish:
    uses: ./.github/workflows/publish-python-package.yml
    with:
      package-dir: python-client
      artifact-name: gabriel-client-dist
    permissions:
      id-token: write
